module.exports.ERROR_CODES = {
    ENTITY: {
        PORTFOLIO: "portfolio",
        COIN: "coin",
        TRANSACTION: "transaction",
        USER: "user",
    },
    EXTRAS: {
        BINANCE: "binance",
        KUCOIN: "kucoin",
    },
    portfolios: {
        creating: "Error creating portfolio",
        deleting: "Error deleting portfolio",
        nonExist: "Portfolio does not exist",
        exists: "Portfolio already exists",
        privilege: "You don't have privilege manage this portfolio",
        thirdParty: "You can't delete a portfolio from 3rd party apps",
        unknown: "Unknown error",
    },
    coins: {
        creating: "Error creating coin",
        deleting: "Error deleting coin",
        updating: "Error updating coin",
        exists: "Coin already exists",
        privilege: "You don't have privilege manage this coin",
        unknown: "Unknown error",
    },
    transactions: {
        creating: "Error creating transaction",
        type: "Not valid transaction type",
        deleting: "Error deleting transaction",
        updating: "Error updating transaction",
        exists: "Transaction already exists",
        nonExist: "Transaction does not exist",
        privilege: "You don't have privilege manage this transaction",
        unknown: "Unknown error",
    },
    users: {
        creating: "Error creating user",
        deleting: "Error deleting user",
        updating: "Error updating user",
        exists: "User with that email already exists",
        nonExist: "User does not exist",
        privilege: "You don't have privilege manage this user",
        unknown: "Unknown error",
        passwordLength: "Password must be at least 8 characters long",
        passwordMatch: "Passwords don't match",
        token: "Invalid token please try again",
        email : "Invalid email",
    },
    binance: {
        update: "Error updating Binance credentials",
        creating : "Error creating Binance portfolio",
        noCredentials : "No credentials found",
        saving: "Error saving Binance portfolio",
        badCredentials: "Error trying to connect with Binance API, try updating your credentials",
        resyncing: "Error resyncing Binance portfolio, check API key and secret in your profile.",
        unknown: "Unknown error",
    },
    kucoin: {
        update: "Error updating Kucoin credentials",
        creating : "Error creating Kucoin portfolio",
        noCredentials : "No credentials found",
        saving: "Error saving Kucoin portfolio",
        badCredentials: "Error trying to connect with Kucoin API, try updating your credentials",
        resyncing: "Error resyncing Kucoin portfolio, check API key and secret in your profile.",
        unknown: "Unknown error",
    },
};
